# EDA

In [13]:
from skimage import io
from PIL import Image
import os
import cv2

In [21]:
image_path = '../data/img/train_jpg/4f029e2a00e892aa2cac27d98b52ef8b13d91471f613c8d3c38e3f29d4da0b0c.jpg'
print(os.path.exists(image_path))
if os.path.exists(image_path):
    print('helo')
    try:
        img = io.imread(image_path)
    except:
        print('hi')
        img = 0

True
helo
hi


In [2]:
import pandas as pd 

In [15]:
df = pd.read_csv('../data/unzipped/train.csv')

In [3]:
import numpy as np

In [22]:
a = np.empty((0, 4))
a.shape

(0, 4)

In [23]:
b = np.ones((2, 4))
b.shape

(2, 4)

In [24]:
np.append(a, b, axis=0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [1]:
import torch

In [2]:
a = torch.zeros(3,5)

In [3]:
a

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
b = a.tolist()

In [11]:
b + b

[[0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0]]

In [5]:
data = pd.read_hdf('../src/imageNet/features/train_image_feature.h5', 'table')

In [6]:
len(data)

1503424

In [7]:
len(df)

NameError: name 'df' is not defined

In [8]:
data

0         1         2         3         4         5         6  \
0        0.059209  0.074902  0.192016  0.005649  0.038234  0.041121  0.041095   
1        0.022944  0.537370  0.061572  0.028897  0.080898  0.029374  0.052467   
2        0.007741  0.233768  0.091479  0.050106  0.177507  0.287048  0.107063   
3        0.243256  0.197528  0.017880  0.020966  0.494946  0.148283  0.151817   
4        0.063006  0.124970  0.062142  0.195248  0.095577  0.039811  0.139859   
5        0.279504  0.043132  0.180559  0.174388  0.067966  0.047067  0.341462   
6        0.112674  0.065986  0.039941  0.000000  0.006630  0.000000  0.013933   
7        0.111626  0.000886  0.015313  0.085365  0.047858  0.173082  0.062614   
8        0.139715  0.005206  0.115586  0.275917  0.134487  0.157457  0.117306   
9        0.104691  0.037941  0.321406  0.011818  0.124935  0.098093  0.025152   
10       0.148127  0.059101  0.132666  0.598703  0.091149  0.187874  0.107182   
11       0.000000  0.078262  0.135586  0.000000  0.059604  0.087805  0.101866   
12       0.032799  0.019258  0.218249  0.070433  0.153256  0.000000  0.015986   
13       0.124966  0.000000  0.009183  0.151401  0.005566  0.006573  0.000277   
14       0.142661  0.020056  0.029536  0.018007  0.005412  0.222019  0.101192   
15       0.000792  0.486285  0.147128  0.044497  0.047185  0.106930  0.185689   
16       0.096569  0.061152  0.136691  0.030365  0.042837  0.145793  0.037474   
17       0.055464  0.000000  0.360436  0.024997  0.069108  0.056995  0.117353   
18       0.000670  0.282131  0.003091  0.102228  0.028072  0.047340  0.002630   
19       0.182160  0.106896  0.087159  0.197373  0.176189  0.106673  0.031475   
20       0.216059  0.007329  0.022516  0.541577  0.206053  0.219774  0.005798   
21       0.000000  0.001369  0.004774  0.000000  0.008352  0.000000  0.009105   
22       0.096151  0.322947  0.077747  0.020481  0.063061  0.064486  0.135458   
23       0.142918  0.024491  0.384851  0.138574  0.158008  0.117621  0.013066   
24       0.112740  0.047964  0.273453  0.202088  0.172464  0.053268  0.050568   
25       0.000000  0.001369  0.004774  0.000000  0.008352  0.000000  0.009105   
26       0.124489  0.216826  0.141083  0.084047  0.243950  0.269596  0.311466   
27       0.255555  0.332828  0.101173  0.302993  0.111770  0.107670  0.178290   
28       0.401180  0.246099  0.218995  0.017716  0.147106  0.256391  0.037577   
29       0.122764  0.410013  0.203955  0.032243  0.322229  0.037022  0.391495   
...           ...       ...       ...       ...       ...       ...       ...   
1503394  0.136701  0.119510  0.297848  0.266980  0.254810  0.105590  0.147336   
1503395  0.005975  0.013734  0.016009  0.000000  0.039858  0.000000  0.000000   
1503396  0.251855  0.235024  0.288849  0.575688  0.160944  0.323171  0.242631   
1503397  0.064560  0.020843  0.042389  0.056657  0.024170  0.066239  0.008208   
1503398  0.064463  0.281023  0.223670  0.252237  0.222846  0.282783  0.409271   
1503399  0.060160  0.012929  0.401493  0.017748  0.298268  0.140723  0.371260   
1503400  0.452408  0.069085  0.294331  0.032327  0.311683  0.057311  0.194751   
1503401  0.093214  0.063931  0.088491  0.009888  0.008781  0.031478  0.046307   
1503402  0.054157  0.396644  0.508525  0.475002  0.159440  0.107337  0.112668   
1503403  0.077897  0.027517  0.037205  0.000000  0.148598  0.290796  0.319850   
1503404  0.075823  0.157810  0.006887  0.111865  0.344233  0.057897  0.048560   
1503405  0.022901  0.017025  0.021673  0.009684  0.127010  0.045409  0.031141   
1503406  0.071564  0.160275  0.106993  0.231720  0.021864  0.094831  0.067409   
1503407  0.096030  0.128489  0.213844  0.478963  0.121092  0.273214  0.344031   
1503408  0.279913  0.040916  0.395255  0.138402  0.100057  0.216460  0.084153   
1503409  0.100255  0.070632  0.346929  0.127063  0.229773  0.070439  0.433838   
1503410  0.077245  0.187324  0.438546  0.209109  0.026833  0.010355  0.040539   
1503411  0.116927  0.210090  0.058788  0.014514

In [18]:
data.shape, df.shape

((1503424, 513), (1503424, 18))

In [19]:
from skimage import io

In [22]:
io.imread('../data/img/train_jpg/97ef0a3c0e690e57cc7a1420f3c7183923ea03b031b783d478af78d7380c3ae9.jpg')

array([[[165, 161, 126],
        [168, 163, 131],
        [170, 165, 133],
        ...,
        [141, 136,  98],
        [137, 132,  94],
        [136, 131,  93]],

       [[158, 154, 119],
        [159, 155, 120],
        [162, 157, 125],
        ...,
        [139, 134,  96],
        [133, 128,  90],
        [129, 124,  86]],

       [[150, 146, 111],
        [151, 147, 112],
        [154, 150, 115],
        ...,
        [141, 135,  99],
        [134, 128,  92],
        [131, 125,  89]],

       ...,

       [[189, 192, 163],
        [202, 205, 176],
        [195, 198, 169],
        ...,
        [162, 158, 123],
        [158, 154, 119],
        [156, 152, 117]],

       [[184, 184, 156],
        [199, 199, 171],
        [192, 192, 164],
        ...,
        [162, 158, 123],
        [159, 155, 120],
        [156, 152, 117]],

       [[175, 175, 147],
        [191, 191, 163],
        [186, 186, 158],
        ...,
        [161, 157, 122],
        [156, 152, 117],
        [152, 148, 113]]

In [10]:
test = pd.read_csv('../data/unzipped/test.csv')

In [14]:
len(test[test['image'].isnull()])

42609

In [15]:
len(test)

508438

In [16]:
testdata= pd.read_hdf('../src/imageNet/features/test_image_feature.h5', 'table')

In [17]:
testdata

0         1         2         3         4         5         6  \
0       0.327080  0.056591  0.163888  0.109098  0.088254  0.380959  0.844922   
1       0.000000  0.090841  0.001950  0.002661  0.013542  0.076072  0.009743   
2       0.006112  0.002288  0.003608  0.043483  0.041158  0.004544  0.000647   
3       0.279712  0.439570  0.254582  0.391621  0.161231  0.141791  0.564441   
4       0.049891  0.074052  0.015897  0.093760  0.001566  0.156946  0.017921   
5       0.082553  0.215581  0.357270  0.004784  0.667984  0.521653  0.040117   
6       0.005887  0.010856  0.000459  0.000011  0.002458  0.001056  0.000000   
7       0.284120  0.036695  0.231025  0.071820  0.009157  0.036132  0.034561   
8       0.136026  0.349755  0.238705  0.309863  0.083712  0.006943  0.002234   
9       0.259734  0.032565  0.097438  0.264950  0.088186  0.167231  0.002307   
10      0.005887  0.010856  0.000459  0.000011  0.002458  0.001056  0.000000   
11      0.005887  0.010856  0.000459  0.000011  0.002458  0.001056  0.000000   
12      0.017363  0.068620  0.815954  0.108690  0.215986  0.082127  0.198740   
13      0.128247  0.009018  0.466005  0.158081  0.232385  0.122648  0.006929   
14      0.081875  0.024009  0.132809  0.080625  0.075170  0.119348  0.058689   
15      0.109019  0.026533  0.125328  0.001091  0.014442  0.071486  0.048215   
16      0.090461  0.109124  0.140997  0.071511  0.033951  0.071076  0.019224   
17      0.283263  0.173579  0.067099  0.091618  0.177798  0.134606  0.026025   
18      0.049076  0.357019  0.000000  0.026711  0.003113  0.004874  0.009047   
19      0.005887  0.010856  0.000459  0.000011  0.002458  0.001056  0.000000   
20      0.107317  0.107920  0.000000  0.091444  0.148159  0.116200  0.085875   
21      0.098967  0.107467  0.353257  0.128987  0.180935  0.119508  0.137360   
22      0.038648  0.207500  0.100198  0.137867  0.124486  0.016879  0.107191   
23      0.149886  0.151512  0.069180  0.242608  0.010832  0.228435  0.066423   
24      0.177172  0.139402  0.351147  0.196366  0.453883  0.241689  0.525677   
25      0.012367  0.195961  0.171425  0.011441  0.284083  0.058012  0.128349   
26      0.005887  0.010856  0.000459  0.000011  0.002458  0.001056  0.000000   
27      0.029182  0.110126  0.077323  0.031114  0.079615  0.110598  0.185116   
28      0.082866  0.027578  0.126554  0.511756  0.253439  0.246834  0.132979   
29      0.092798  0.109376  0.021650  0.276364  0.044844  0.094036  0.134606   
...          ...       ...       ...       ...       ...       ...       ...   
508408  0.563052  0.014509  0.071078  0.220207  0.103667  0.198855  0.028566   
508409  0.113283  0.024367  0.000000  0.008759  0.005646  0.000000  0.033353   
508410  0.012263  0.000786  0.000000  0.000000  0.001195  0.000000  0.000000   
508411  0.012263  0.000786  0.000000  0.000000  0.001195  0.000000  0.000000   
508412  0.235361  0.173148  0.056255  0.148805  0.021186  0.343199  0.143739   
508413  0.045995  0.275006  0.377644  0.014516  0.302959  0.047575  0.078327   
508414  0.111414  0.025349  0.273800  0.201160  0.046380  0.013690  0.010804   
508415  0.202177  0.113803  0.325658  0.051963  0.159121  0.119277  0.011455   
508416  0.147529  0.031887  0.066651  0.171174  0.015545  0.177858  0.007817   
508417  0.089567  0.169347  0.031146  0.000000  0.002767  0.214539  1.022574   
508418  0.086371  0.082243  0.102221  0.229879  0.189489  0.073994  0.047311   
508419  0.010001  0.530759  0.064339  0.069413  0.088878  0.115912  0.035931   
508420  0.072307  0.211139  0.072124  0.207614  0.079813  0.021805  0.008078   
508421  0.028618  0.100109  0.115859  0.088059  0.464275  0.074928  0.000895   
508422  0.218531  0.063920  0.077968  0.018381  0.016623  0.024254  0.029430   
508423  0.091970  0.053072  0.190496  0.180140  0.204153  0.197739  0.035685   
508424  0.142932  0.078386  0.275704  0.190018  0.146538  0.134488  0.395017   
508425  0.334247  0.123325  0.196677  0.073141  0.481649  0.258839  0.321881   
508426  0.34250