# EDA

In [13]:
from skimage import io
from PIL import Image
import os
import cv2

In [21]:
image_path = '../data/img/train_jpg/4f029e2a00e892aa2cac27d98b52ef8b13d91471f613c8d3c38e3f29d4da0b0c.jpg'
print(os.path.exists(image_path))
if os.path.exists(image_path):
    print('helo')
    try:
        img = io.imread(image_path)
    except:
        print('hi')
        img = 0

True
helo
hi


In [6]:
import pandas as pd 

In [15]:
df = pd.read_csv('../data/unzipped/train.csv')

In [1]:
import numpy as np

In [22]:
a = np.empty((0, 4))
a.shape

(0, 4)

In [23]:
b = np.ones((2, 4))
b.shape

(2, 4)

In [24]:
np.append(a, b, axis=0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [1]:
import torch

In [2]:
a = torch.zeros(3,5)

In [3]:
a

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
b = a.tolist()

In [11]:
b + b

[[0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0]]

In [13]:
data = pd.read_hdf('../src/imageNet/image_feature.h5', 'table')

In [14]:
len(data)

1503424

In [16]:
len(df)

1503424

In [17]:
data

0         1         2         3         4         5         6  \
0        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
1        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
2        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
3        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
4        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
5        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
6        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
7        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
8        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
9        0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
10       0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
11       0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
12       0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
13       0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
14       0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
15       0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041786   
16       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
17       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
18       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
19       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
20       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
21       0.014887  0.100345  0.564521  0.000000  0.060993  0.105143  0.000000   
22       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
23       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
24       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
25       0.014887  0.100345  0.564521  0.000000  0.060993  0.105143  0.000000   
26       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
27       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
28       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
29       0.167398  0.252941  0.172232  0.161101  0.223861  0.181226  0.086072   
...           ...       ...       ...       ...       ...       ...       ...   
1503394  0.112310  0.241901  0.164482  0.073864  0.156258  0.140382  0.073272   
1503395  0.000000  0.118157  0.553744  0.023159  0.111257  0.138658  0.000000   
1503396  0.112310  0.241901  0.164482  0.073864  0.156258  0.140382  0.073272   
1503397  0.112310  0.241901  0.164482  0.073864  0.156258  0.140382  0.073272   
1503398  0.112310  0.241901  0.164482  0.073864  0.156258  0.140382  0.073272   
1503399  0.112310  0.241901  0.164482  0.073864  0.156258  0.140382  0.073272   
1503400  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503401  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503402  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503403  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503404  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503405  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503406  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503407  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503408  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503409  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503410  0.104318  0.244113  0.308299  0.205192  0.075423  0.167852  0.041785   
1503411  0.104318  0.244113  0.308299  0.205192

In [18]:
data.shape, df.shape

((1503424, 513), (1503424, 18))

In [19]:
from skimage import io

In [22]:
io.imread('../data/img/train_jpg/97ef0a3c0e690e57cc7a1420f3c7183923ea03b031b783d478af78d7380c3ae9.jpg')

array([[[165, 161, 126],
        [168, 163, 131],
        [170, 165, 133],
        ...,
        [141, 136,  98],
        [137, 132,  94],
        [136, 131,  93]],

       [[158, 154, 119],
        [159, 155, 120],
        [162, 157, 125],
        ...,
        [139, 134,  96],
        [133, 128,  90],
        [129, 124,  86]],

       [[150, 146, 111],
        [151, 147, 112],
        [154, 150, 115],
        ...,
        [141, 135,  99],
        [134, 128,  92],
        [131, 125,  89]],

       ...,

       [[189, 192, 163],
        [202, 205, 176],
        [195, 198, 169],
        ...,
        [162, 158, 123],
        [158, 154, 119],
        [156, 152, 117]],

       [[184, 184, 156],
        [199, 199, 171],
        [192, 192, 164],
        ...,
        [162, 158, 123],
        [159, 155, 120],
        [156, 152, 117]],

       [[175, 175, 147],
        [191, 191, 163],
        [186, 186, 158],
        ...,
        [161, 157, 122],
        [156, 152, 117],
        [152, 148, 113]]